### ISSUE TITLE
Typo on Olympias

### ISSUE THREAD

**Issue by Faraaz-Beyabani** [tom-james-watson/wikitrivia-scraper#12]
![image](https://github.com/tom-james-watson/wikitrivia-generator/assets/35716327/03f446a4-0d23-4f86-9d03-3e13be7a4e7d)

**Comment by tom-james-watson** [comment]
Thanks. Though this is the incorrect place to report this. At the moment we don't have an easy way to resolve these so will just close this out. The fix is to update our underlying data.
